// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_U_n
List compute_U_n(NumericVector X_n, List phi, List psi_n_mu_n, List U_n, NumericVector cumsum_Ms, NumericVector cumsum_Ms_Ms, int num_ct);
RcppExport SEXP _BLEND_compute_U_n(SEXP X_nSEXP, SEXP phiSEXP, SEXP psi_n_mu_nSEXP, SEXP U_nSEXP, SEXP cumsum_MsSEXP, SEXP cumsum_Ms_MsSEXP, SEXP num_ctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X_n(X_nSEXP);
    Rcpp::traits::input_parameter< List >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< List >::type psi_n_mu_n(psi_n_mu_nSEXP);
    Rcpp::traits::input_parameter< List >::type U_n(U_nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cumsum_Ms(cumsum_MsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cumsum_Ms_Ms(cumsum_Ms_MsSEXP);
    Rcpp::traits::input_parameter< int >::type num_ct(num_ctSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_U_n(X_n, phi, psi_n_mu_n, U_n, cumsum_Ms, cumsum_Ms_Ms, num_ct));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BLEND_compute_U_n", (DL_FUNC) &_BLEND_compute_U_n, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_BLEND(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
