# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_U_n <- function(X_n, phi, psi_n_mu_n, U_n, cumsum_Ms, cumsum_Ms_Ms, num_ct) {
    .Call('_BLEND_compute_U_n', PACKAGE = 'BLEND', X_n, phi, psi_n_mu_n, U_n, cumsum_Ms, cumsum_Ms_Ms, num_ct)
}

